### ISSUE TITLE
Installation dun workspace sur le beagleboard

### ISSUE THREAD

**Issue by salco** [walkingmachinegraveyard/sara_robot#11]
**Objectif**:
Développer l'interface tactile de sara facilement et pouvoirs la modifier aussi facilment.
Developper du code pour utiliser le hardware du beagleboard
Developper du code facilement peut importe le laguage qui est neccessaire dans le future.
Detailler la demarche pour éviter a quelqu’un dautre de passer des nuits a crosscopiler des OS qui marche pas.

**Probleme**:
1) Le stock pour lecrant ce trouve juste sur lecrant donc pas vraiment de monde qui a fait evoluer la chose depuis
2) L'information et les images son outdated et la majeurs partie des problemes vienne de la
3) J'ai cross-compiler que pour un seul appareil a date donc je suis pas le Gregory Charles du compilage

**La mise en place**:

- Jai fait un wiki avec les mesure fonctionnel et l'information expliquant les ancienes problématique
- Jai creer un moyen de partager les fichier entre beagle et l'ordi (mais des modification future son requise)
- J'ai trouver un jolie [How-to](http://exploringbeaglebone.com)

**Ou j'en suis**:

1. Je compte utiliser le debian qui était déjà dans le beagle parce que il a l’aire stable et plus meilleur a combler nos futur besoin. 
2. Je vais suivre le tutoriel pour voir ce que ca donne et si on peut le suivre pour développer plus tard

**Plus tard**:
- Faire un apli de base pour montrer la fesabiliter(il en exite deja plein)
- Faire un issue pour installer ros dedans
- Faire fonction le can avec ou sans Qt (doit au prealable choisir de facon certaine que le linux et que la version du stok est ok avant parce que si on doit changer ca va compliquer le devlopement du Can)

**Comment by salco** [comment]
Un des problem est que les version de GCC son differante, et que lenvironement de devolopement sur PC est amd64 ubuntu et sur le BBB armv7 debian(custom version).
Les gros probleme vienne d'une difficulter a recuperer les vieux tool ou la mise en place de nouveau pour ne pas avoir a struggle trop dans le futur.

**Comment by salco** [comment]
jai reussi a faire un apli fenetre fonctionel et jutilise Qt-5.7.0 et gcc 14.04

Mes referance:

> Le file que jai modifier provien de la
> http://neovox.advancedmagic.de/?p=51
> bonne demarche mais juste comme referance.  
> http://exploringbeaglebone.com/chapter11/  
> a utiliser pour savoir quel lib est manquant  
> http://doc.qt.io/qt-5/linux-requirements.html  
> refrance basic
> https://eewiki.net/display/linuxonarm/BeagleBone+Black
> http://stackoverflow.com/questions/17106315/failed-to-load-platform-plugin-xcb-while-launching-qt5-app-on-linux-without

autre:
http://doc.qt.io/qt-5/linux-requirements.html
http://processors.wiki.ti.com/index.php/Building_Qt
https://forum.openframeworks.cc/t/trying-to-compile-an-example-on-tegra-jetson-tk1/16128

> a propos de xcb
> http://stackoverflow.com/questions/25822875/configure-error-the-test-for-linking-against-libxcb-and-support-libraries-fai
> https://wiki.qt.io/Building_Qt_5_from_Git  
> https://groups.google.com/forum/#!topic/beagleboard/mb1R6NF5RH4

**Comment by salco** [comment]
le file modifier est sur mon compte: https://github.com/salco/crosscompile-qt-for-arm  
Il permet d'installer tout en utilisant jsute la console. apres il faut suivre les etapes du site de reference (neovox)

**Comment by salco** [comment]
cependant jai toujours des soucis de linker mais dans lenseble tout roule

**Comment by gregoirefra** [comment]
Pourquoi il est pas un gist plutot ou de quoi du genre qui pourrait être linker a l'organisation?

**Comment by salco** [comment]
J'ai jamais utiliser et on poura en faire un fork pour walking une fois que le launcher sera terminer. Il ny a pas vraiment de modif a faire dans le future, probablement juste des chose dergonomie ou d'update des version telecharger.

**Comment by gortium** [comment]
Pas obligé d'être un gist, mais ce serrais mieux de mettre le travail en rapport au club dans l'organisation pour ne pas avoir a chercher si quelqu'un d'autre en a besoin.

**Comment by salco** [comment]
problem au niveau des link, je doit declarer le dossier des libQt `Set LD_LIBRARY_PATH to /opt/Qt-5.7.0/lib/` parce que il ne fonctionne pas autrement et je doit copier /opt/Qt-5.7.0/plugins/platforms dans le dossier de lexecutable

**Comment by salco** [comment]
Donc resumer:
1. aller dans le dossier contenant le rootfs du beagle (je lai mount dans media/wm/rootfs)
2. utiliser le scrip pour avoir Qt et tout
3. metre le Qt compiler dans /opt/ du beagle
4. faire un projet
5. utiliser LD_LIBRARY_PATH et copier les plugins que on a besoin

voila un belle environement host:Ubuntu remote:arm/Debian

**Comment by gortium** [comment]
Et pourquoi debian et non ubuntu? il va falloir installer ros sur le beagle donc ubuntu serrais plus compatible.
