### ISSUE TITLE
Choix du Kernel pour beagleboard black

### ISSUE THREAD

**Issue by salco** [walkingmachinegraveyard/sara_robot#12]
Pour le moment on a l'ancien kernel debian qui est copier et dans le drive et il y a agstrom qui fonctionne aussi.
J'ai decider que lancien debian etait une meilleur alternative parce quil semble plus complet et permet eventuelment dutiliser Ros(au besoin).
Je ne sais pas si il est disponible pour l'autre version(recherche rapide et jai rien trouver)

Je laisse lissu pour en discuter au besoin mais la decission a deja été prise et sauf raison majeur il est preferable de ne pas rechanger.

**Comment by salco** [comment]
Le choix est fait on prend **Debian**, si jamais on utilise le raspberry pi dans le futur on aura deja une partie du travail de fait et les commande de debian ressemble souvent a ceux de ubuntu.

**Comment by gortium** [comment]
Pourquoi debian et pas ubuntu? Les ros wiki conseil ubuntu pour l'installation sur arm. Peut-être que debian est aussi compatible, mais pourquoi prendre la chance? http://wiki.ros.org/indigo/Installation/UbuntuARM

**Comment by salco** [comment]
si jamais on a un raspberri pi il utilise une suite debian, de plus jai vue que cetait fesable de metre ros-indigo sur debian.
